private-events/config/routes.rb
Rails.application.routes.draw do
  resources :users,  only: [:new, :create, :show]
  resources :events, only: [:new, :create, :show, :index]

  get     'signin'  => 'sessions#new'
  post    'signin'  => 'sessions#create'
  delete  'signout' => 'sessions#destroy'

end

private-events/app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :creator, :class_name => "User"
	has_many :invitations, :foreign_key => :attended_event_id
	has_many :attendees, :through => :invitations

	scope :past, 		 -> { where("date < ?", DateTime.now) }
	scope :upcoming, -> { where("date >= ?", DateTime.now) }
end

private-events/app/models/invitation.rb
class Invitation < ActiveRecord::Base
	belongs_to :attendee, :class_name => "User"
	belongs_to :attended_event, :class_name => "Event"

	validates :attendee_id, presence: true
	validates :attended_event_id, presence: true
end

private-events/app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true, length: { in: 5..30 }
	validates :email, presence: true, uniqueness: true,
										length: { in: 5.. 30 }

	has_many :events, :foreign_key => "creator_id"
	has_many :invitations, :foreign_key => :attendee_id
	has_many :attended_events, :through => :invitations 
end

private-events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include EventsHelper
end

private-events/app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :signed_in?, only: [:new, :create]

	def index
		@events = Event.all
	end

	def new
	end

	def create
		@event = current_user.events.build(event_params)
		if @event.save
			@event.attendees << current_user
			flash[:success] = 'Event created!'
			redirect_to @event
		else
			flash.now[:danger] = 'Could not create event!'
			render 'new'
		end
	end

	def show
		@event = Event.find_by(id: params[:id])
	end

	private
		def event_params
			params.require(:event).permit(:name, :location, :date, :description)
		end
end

private-events/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(name: params[:session][:name])
  	if user
  		sign_in(user)
  		redirect_to user
  	else
  		flash.now[:danger] = 'That user does not exist!'
  		render 'new'
  	end
  end

  def destroy
  	sign_out if signed_in?
  	#update below to route to events#index later on
  	redirect_to signin_path
  end
end
	

private-events/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = 'Account created!'
			sign_in(@user)
			redirect_to @user
		else
			flash.now[:danger] = 'Could not create account!'
			render 'new'
		end
	end

	def show
	end

	private
		def user_params
			params.require(:user).permit(:name, :email)
		end
end

private-events/app/helpers/application_helper.rb
module ApplicationHelper

end

private-events/app/helpers/events_helper.rb
module EventsHelper
	def prev_events
		current_user.attended_events.where("date < ? ", DateTime.now)
	end

	def upcoming_events
		current_user.attended_events.where("date >= ? ", DateTime.now)
	end
end

private-events/app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		session[:user_id] = user.id
	end

	def sign_out
		session.delete(:user_id)
	end

	def current_user
		current_user ||= User.find_by(id: session[:user_id])
	end

	def signed_in?
		!current_user.nil?
	end
end

private-events/app/helpers/users_helper.rb
module UsersHelper
end

private-events/app/views/events/index.html.erb
<h1>All Events</h1>

<h3>Upcoming Events</h3>
<% Event.upcoming.each do |event| %>
	<ul>
	<strong><%= event.name %></strong>
		<li>Created By:	  <%= event.creator.name %></li>
		<li>Date:					<%= event.date %></li>
		<li>Location:			<%= event.location%></li>
		<li>Description: 	<%= event.description%></li>
	</ul>
	<%= link_to "Details", event %>
<% end %>

<h3>Past Events</h3>
<% Event.past.each do |event| %>
	<ul>
	<strong><%= event.name %></strong>
		<li>Created By:	  <%= event.creator.name %></li>
		<li>Date:					<%= event.date %></li>
		<li>Location:			<%= event.location%></li>
		<li>Description: 	<%= event.description%></li>
	</ul>
	<%= link_to "Details", event %>
<% end %>

private-events/app/views/events/new.html.erb
<h1>Create a New Event:</h1>

<%= form_for(current_user.events.build) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, placeholder: "Ex. Punish Bart" %>

	<%= f.label :date %>
	<%= f.date_field :date %>

	<%= f.label :location %>
	<%= f.text_field :location, placeholder: "Ex. Springfield" %>

	<%= f.label :description %>
	<%= f.text_area :description, placeholder: "Bart is up to no good and Marge wants me to punish him. 
																							Come watch as I show you what good parenting is!", 
																							rows: 7, cols: 25 %>

	<%= f.submit "Create Event" %>
<% end %>

private-events/app/views/events/show.html.erb
<% event = Event.find_by(id: params[:id]) %>
<h1><%= event.name %></h1>
<ul>
	<li><%= event.date %></li>
	<li><%= event.location %></li>
</ul>

<p><%= event.description %></p>
<p><strong>Created By <%= event.creator.name %></strong></p>

<h3>List of Attendees</h3>
<% if event.attendees.empty? %>
	<p><strong>No attendees yet.</strong></p>
<% end %>

<ul>
<% event.attendees.each do |attendee| %>
	<li><%= attendee.name %></li>
<% end %>
</ul>

private-events/app/views/layouts/_header.html.erb
<% if signed_in? %>
	<p>Signed in as <strong><%= current_user.name %></strong></p>
	<%= link_to "Sign Out", signout_path, method: :delete %>
	<%= link_to "Profile", current_user %>
<% else %>
	<%= link_to "Sign Up", new_user_path %>
	<%= link_to "Sign In", signin_path %>
<% end %>

<%= link_to "Events", events_path %>

private-events/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title>PrivateEvents</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<br>
		<% flash.each do |message_type, message| %>
			<%= message %>
		<% end %>

		<%= yield %>

		<%= debug(params) if Rails.env.development? %>
	</body>
</html>

private-events/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

	<div>
		The form contains <%= pluralize(object.errors.count, 'error') %>
	</div>

	<ul>
		<% object.errors.full_messages.each do |full_msg| %>
			<li><%= full_msg %></li>
		<% end %>
	</ul>

<% end %>

private-events/app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :email %>
	<%= f.email_field :email %>

	<%= f.submit "Create Account" %>
<% end %>

private-events/app/views/users/show.html.erb
<h1>Profile Page for <%= current_user.name %></h1>

<h2>My Created Events:</h2>

<% unless current_user.events.empty? %>
	<ul>
	<% current_user.events.each do |event| %>
		<li><%= event.date.to_formatted_s(:long_ordinal) %>	|	<%= event.name %></li>
		<%= link_to "Details", event %>
	<% end %>
	</ul>
<% end %>

<%= link_to "Make a New Event", new_event_path %>

<h2>Upcoming Events:</h2>
<% if upcoming_events.empty? %>
	<p><strong>No upcoming events.</strong></p>

<% else %>
	<% upcoming_events.each do |event| %>
		<li><%= event.date.to_formatted_s(:long_ordinal) %> | <%= event.name %></li>
	<% end %>
<% end %>

<h2>Previously Attended Events:</h2>
<% if prev_events.empty? %>
	<p><strong>No previously attended events.</strong></p>

<% else %>
	<% prev_events.each do |event| %>
		<li><%= event.date.to_formatted_s(:long_ordinal) %> | <%= event.name %></li>
	<% end %>
<% end %>